---
- name: Download statically linked cfssl binary
  get_url:
    url: "https://pkg.cfssl.org/{{ cfssl_version }}/cfssl_{{ cfssl_os }}-{{ cfssl_arch }}"
    dest: "{{ cfssl_bin_directory }}/cfssl"
    mode: 0755
    owner: "{{ cfssl_owner }}"
    group: "{{ cfssl_group }}"
    checksum: "{{ cfssl_checksum }}"
  tags:
    - cfssl

- name: Download statically linked cfssljson binary
  get_url:
    url: "https://pkg.cfssl.org/{{ cfssl_version }}/cfssljson_{{ cfssl_os }}-{{ cfssl_arch }}"
    dest: "{{ cfssl_bin_directory }}/cfssljson"
    owner: "{{ cfssl_owner }}"
    group: "{{ cfssl_group }}"
    checksum: "{{ cfssljson_checksum }}"
    mode: 0755
  tags:
    - cfssl
