---
- name: Setup cfssl
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      ansible.builtin.raw: |
        apt-get update
        apt-get -y install ca-certificates python3
      register: result
      changed_when: false
      failed_when:
        - result.rc != 0

    - name: Call setup
      ansible.builtin.setup:

    - name: Include cfssl role
      ansible.builtin.include_role:
        name: githubixx.cfssl
