---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: test-cfssl-ubuntu2004
    image: ubuntu:20.04
    pre_build_image: true
  - name: test-cfssl-ubuntu1804
    image: ubuntu:18.04
    pre_build_image: true
  - name: test-cfssl-debian10
    image: debian:10
    pre_build_image: true
  - name: test-cfssl-debian11
    image: debian:11
    pre_build_image: true

provisioner:
  name: ansible

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
